### PR TITLE
Update react-onclickoutside to the latest version in order to work with React 16

### PR DESCRIPTION
**Pull request by ilovebeatles**

### CODE REVIEW

**Comment by joehoyle** [comment]
@ilovebeatles why was this closed?

**Comment by ilovebeatles** [comment]
@joehoyle Sorry, that was buggy implementation, so I decided to switch to another library.

**Comment by joehoyle** [comment]
@ilovebeatles out of interest, what did you switch to?

**Comment by ilovebeatles** [comment]
@joehoyle https://www.npmjs.com/package/react-two-way-querybuilder

**Pull request closed without merging**
